const test = require("node:test");
const assert = require("node:assert/strict");
require("../torn-market-edge.user.js");
const E = globalThis.__MARKET_EDGE_TEST__;
function settings(overrides = {}) { return { ...E.DEFAULTS, availableCapital:1_000_000_000, maxCapitalOpportunity:500_000_000, maxCapitalItem:500_000_000, minimumROI:0.02, minimumProfit:0, minimumDiscount:0, safetyHaircut:0, bazaarDiscount:0, allowedHistoricalPremium:1.01, itemMarketUndercut:0, maxVolatility:0.03, minimumGreenConfidence:"VERY LOW", ...overrides }; }
function snapshot(listings, anchor, cacheAgeSeconds=5, extra={}) { return { itemId:1,itemName:"Test item",itemType:"Drug",averagePrice:anchor,cacheTimestamp:Math.floor(Date.now()/1000)-cacheAgeSeconds,listings:listings.map(([price,quantity=1])=>({price,quantity})),lowestPrice:listings[0]?.[0]??null,secondPrice:listings[1]?.[0]??null,calculatedMarketAnchor:anchor,depthMetrics:{listingCount:listings.length,top20Quantity:listings.reduce((sum,[,qty=1])=>sum+qty,0)},supportedCommodity:true,...extra}; }
function history(fair,count=50,volatility=0.005){return{historicalFairValue:fair,oneDay:{count,medianAnchor:fair,volatility},sampleConfidence:count>=50?"HIGH":count>=15?"MEDIUM":count>=5?"LOW":"VERY LOW"};}
test("A obvious arbitrage",()=>{const r=E.evaluatePrefixes(snapshot([[800000,10],[850000,100],[851000,100]],850000),history(850000),settings({safetyHaircut:.01,bazaarDiscount:.01}));assert.ok(r.best);assert.equal(r.best.prefixCount,1);assert.equal(r.best.quantityBought,10);assert.equal(r.best.averageBuyPrice,800000);assert.ok(r.best.expectedProfit>0);});
test("B fake gap",()=>{const r=E.evaluatePrefixes(snapshot([[800000,1],[1200000,1],[1210000,1]],1200000),history(810000),settings({safetyHaircut:.01}));assert.ok(r.best);assert.ok(r.best.exit.exitAnchor<=818100);assert.ok(r.best.exit.conservativeExitPrice<820000);});
test("C fee destroys",()=>{assert.equal(E.itemMarketNetFor(103,1),97);assert.ok(E.itemMarketNetFor(103,1)-100<0);});
test("D bazaar profitable",()=>{const s=snapshot([[103,100],[104,100]],103),h=history(103);const a=E.evaluateDirectBuy({buyPrice:100,quantity:1,snapshot:s,historyStats:h,settings:settings({bazaarEnabled:true})});const b=E.evaluateDirectBuy({buyPrice:100,quantity:1,snapshot:s,historyStats:h,settings:settings({bazaarEnabled:false})});assert.equal(a.routes.bestRoute,"Bazaar");assert.ok(a.expectedProfit>0);assert.ok(b.expectedProfit<0);});
test("E huge qty capital",()=>{const r=E.evaluatePrefixes(snapshot([[800000,1000],[850000,100],[851000,100]],850000),history(850000),settings({maxCapitalOpportunity:25000000,maxCapitalItem:50000000}));assert.equal(r.best,null);});
test("F no history",()=>{const r=E.evaluatePrefixes(snapshot([[80,10],[100,100],[101,100]],100),{historicalFairValue:null,oneDay:{count:0,volatility:null}},settings({minimumGreenConfidence:"MEDIUM",safetyHaircut:0,bazaarDiscount:0}));assert.ok(r.best);assert.ok(["VERY LOW","LOW"].includes(r.best.confidence.label));assert.notEqual(r.best.classification.state,"GREEN");});
test("G volatile",()=>{const r=E.evaluatePrefixes(snapshot([[100,10],[120,100],[121,100],[122,100]],120),history(120,50,.10),settings({minimumGreenConfidence:"VERY LOW",maxVolatility:.03}));assert.ok(r.best);assert.ok(r.best.expectedProfit>0);assert.equal(r.best.classification.state,"YELLOW");});
test("H stale",()=>{const r=E.evaluatePrefixes(snapshot([[100,10],[120,100],[121,100],[122,100]],120,600),history(120),settings({minimumGreenConfidence:"VERY LOW"}));assert.ok(r.best);assert.equal(r.best.confidence.freshness.label,"STALE");assert.equal(r.best.classification.state,"YELLOW");});
test("I single listing",()=>{const r=E.evaluatePrefixes(snapshot([[100,10]],100),history(100),settings());assert.equal(r.best,null);assert.equal(r.all.length,0);});
test("J unsupported equipment",()=>{const n=E.normalizeMarketResponse(99,{itemmarket:{item:{id:99,name:"Special Rifle",type:"Weapon",average_price:10000000},listings:[{price:9000000,amount:1,item_details:{damage:50,accuracy:60}}],cache_timestamp:Math.floor(Date.now()/1000)}});assert.equal(n.supportedCommodity,false);});
